
###
POST http://localhost:3152/user/register
Content-Type: application/json

{
  "f_name": "Jamal",
  "l_name": "San",
  "email": "jamal13@uxd.com",
  "password": "jamal123"
}

###
POST http://localhost:3143/user/login
Content-Type: application/json
{
  "email": "jamal13@uxd.com",
  "password": "jamal123"
}


