POST https://bdtmp.ultra-x.jp/ems_backend/system-admin/get-visitor-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtYWplZHVsQGdtYWlsLmNvbSIsInJvbGUiOiJzeXN0ZW1fYWRtaW4iLCJpYXQiOjE3MjgwMjM5NzgsImV4cCI6MTczNTc5OTk3OH0.0Gyh8GlEwWzB3r9aBAh5mEYXTypn2yN4x7aKshr16BE
Content-Type: application/json

{
   "paginationData":{
        "itemsPerPage": "5",
        "currentPageNumber":0 ,
        "sortOrder": "asc",
        "filterBy": ""
    }
}

###
# POST https://bdtmp.ultra-x.jp/ems_backend/system-admin/get-user-data
POST http://localhost:4560/system-admin/get-user-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtYWplZHVsQHV4ZC5jby5qcCIsInJvbGUiOiJzeXN0ZW1fYWRtaW4iLCJpYXQiOjE3MjgwMjQ1MDEsImV4cCI6MTczNTgwMDUwMX0.kW2Tki2Z-PQLTW7z-jJtzCPM74x0izK_gQnDo407o-w
Content-Type: application/json

{
    "role":"exhibitor",
   "paginationData":{
        "itemsPerPage": "5",
        "currentPageNumber":0 ,
        "sortOrder": "asc",
        "filterBy": ""
    }
}