POST https://bdtmp.ultra-x.jp/ems_backend/system-admin/get-visitor-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtYWplZHVsQGdtYWlsLmNvbSIsInJvbGUiOiJzeXN0ZW1fYWRtaW4iLCJpYXQiOjE3MzA3OTQxNjIsImV4cCI6MTczODU3MDE2Mn0.Igyv5BVT2fSf4hDqZgCjmvfaMDoc-_fAtlUeURi3FYs
Content-Type: application/json

{
   "paginationData":{
        "itemsPerPage": "10",
        "currentPageNumber":0 ,
        "sortOrder": "asc",
        "filterBy": ""
    }
}

###
# POST https://bdtmp.ultra-x.jp/ems_backend/system-admin/get-user-data
POST http://localhost:4560/system-admin/get-user-data
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJtYWplZHVsQGdtYWlsLmNvbSIsInJvbGUiOiJzeXN0ZW1fYWRtaW4iLCJpYXQiOjE3MzA3OTQxNjIsImV4cCI6MTczODU3MDE2Mn0.Igyv5BVT2fSf4hDqZgCjmvfaMDoc-_fAtlUeURi3FYs
Content-Type: application/json

{
    "role":"exhibitor",
   "paginationData":{
        "itemsPerPage": "5",
        "currentPageNumber":0 ,
        "sortOrder": "asc",
        "filterBy": ""
    }
}